application: customizableeventapp
version: 1
runtime: php
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /Speakers
  script: Speakers.php
- url: /Events
  script: Events.php
- url: /Directions
  script: Directions.php
- url: /.*
  script: Overview.php