application: customizableeventapp
version: 1
runtime: php
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /newlist
  script: newlist.php
- url: /makenewlist
  script: makenewlist.php
- url: /.*
  script: mainapp.php